# 日志配置
logging:
    # 设置日志文件存放目录为当前登录用户的主目录
    file: ${user.home}/logs/multiple-datasource.log
    # 下面设置单个日志文件最大为10MB,只保存30天内日志，超过时间自动删除
    file.max-size: 10MB
    file.max-history: 30
    level:
        # root 级别即项目的所有日志默认输出为info
        root: info
        # 本项目开发使用debug,测试上线后使用info
        com.bearcat2: debug

spring:
    multiple:
        datasource:
            # 配置获取连接等待超时的时间,单位毫秒
            max-wait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置连接校验
            validationQuery: SELECT 1
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            # 打开PSCache，指定每个连接上PSCache的大小
            poolPreparedStatements: true
            maxPoolPreparedStatementPerConnectionSize: 20
            # 配置监控统计拦截的filters
            filters: stat,wall
            async-init: true

            # 配置第一个数据源
            ds1:
                # 配置 用户名、密码、url和驱动类名称
                username: root
                password: 123
                url: jdbc:mysql://127.0.0.1:3306/ds1?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
                driver-class-name: com.mysql.cj.jdbc.Driver
                # 配置初始化大小、最小、最大连接数
                initial-size: 5
                min-idle: 5
                max-active: 10

            # 配置第二个数据源
            ds2:
                # 配置 用户名、密码、url和驱动类名称
                username: root
                password: 123
                url: jdbc:mysql://127.0.0.1:3306/ds2?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
                driver-class-name: com.mysql.cj.jdbc.Driver
                # 配置初始化大小、最小、最大连接数
                initial-size: 5
                min-idle: 5
                max-active: 10